### PR TITLE
[bug] Fixing build pipeline and windows binary 

### PR DESCRIPTION
**Pull request by ctr26**
Adding loads of CICD to build the executables

### CODE REVIEW

**Comment by ctr26** [comment]
@IvanHCenalmor 

I've commented the macOS build for now, we probably don't need it as people can only realistically train on windows and linux

**Comment by ctr26** [comment]
@IvanHCenalmor , could someone with a windows machine double check that the .bat file works with my changes please?

**Comment by IvanHCenalmor** [comment]
Hi Craig! I have tested the Windows `.bat` file and it seems that is correctly working with the new changes.
Also, one quick question, do you think that moving some of the new files to another folder that is not the main one would give any problem? If so, I merge the pull request and put them maybe in the `.tools` folder.

**Comment by ctr26** [comment]
The launcher.py is currently expecting to be in the root directory. Launcher would need modifying to go in .tools

Makefiles are also usually in the root dir

**Pull request merged**
